{% set name = "rayint" %}
{% set version = "cuda" %}
{% set commit = "d5a8126aebb98c68b2b98bea05fcc8cebb6a2fb9" %}
{% set mve_version = "master" %}
{% set mve_commit = "55eb94f34f82694e0f25a7f235c25a06acc0bfae" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/nmoehrle/rayint/archive/{{ commit }}.tar.gz
    sha256: 54cfd7c962504deb7c8d3afc66123dfcb854a9ae00e492d87a3d9f361f50c5a0
    patches:
      - mve.patch
  - fn: mve-{{ mve_version }}.tar.gz
    url: https://github.com/simonfuhrmann/mve/archive/{{ mve_commit }}.tar.gz
    sha256: a1880f243b38ec0b669aa638225e45f300c508e621b1ee0fb3d444a665a512cc
    folder: elibs/mve

build:
    number: 0

requirements:
  build:
    # - {{ compiler("c") }}
    # - {{ compiler("cxx") }}
    - cmake
    - ninja
  host:
    - libpng
    - openjpeg
    - libtiff
    - mve {{ mve }}

test:
  commands:
    - test -f $PREFIX/bin/raycast

about:
  home: https://github.com/nmoehrle/rayint
  license: BSD 3-Clause
  summary: Simple ray intersection library similar to coldet - succedeed by libacc

extra:
  recipe-maintainers:
    - v-turin
